version: "3.9"
services:
  api:
    build:
      context: ./packages/api
      dockerfile: ./dockerfile
    ports:
      - '5000:5000'
    environment:
      - WORKERS=2
      - PORT=5000
      - FLASK_ENV=development
      - FLASK_APP=app.py
  # webapp:
  #   build:
  #     context: ./packages/webapp
  #     dockerfile: ./dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - API_URL=http://api:5000
